"""Iter 38 / Phase Polish — invoice PDF: single-line big total + logo space."""
import sys, io
sys.path.insert(0, "/app/backend")
import pdfplumber
import finance as finance_mod


def _make(amount: float):
    invoice = {
        "id": "INV-TEST-001",
        "invoice_no": "INV-2026-7777",
        "issued_at": "2026-01-15",
        "due_date": "2026-02-15",
        "status": "ISSUED",
        "amount": amount,
        "tax_percent": 0,
        "discount": 0,
        "notes": "Auto-generated by iter38 polish test.",
        "items": [{"description": "Phase C delivery — milestone payment",
                    "qty": 1, "rate": amount}],
    }
    finance = {
        "project_id": "PRJ-TEST",
        "project_name": "TEST QA Project — Iter 38",
        "category": "engineering",
        "payment_type": "one_time",
        "currency": "INR",
        "client_name": "TEST QA Client Pvt Ltd",
        "client_emails": [{"email": "test_qa_client@example.com", "primary": True}],
        "billing_address": "221B Baker Street\nLondon",
        "gst_number": "29ABCDE1234F2Z5",
        "payments": [],
        "locked_budget": amount,
    }
    return invoice, finance


def _total_line(pdf_bytes):
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as doc:
        text = doc.pages[0].extract_text() or ""
    lines = [ln for ln in text.splitlines() if "TOTAL DUE" in ln.upper()]
    return lines, text


def test_invoice_pdf_total_due_single_line_7digit():
    inv, fin = _make(1234567.89)
    pdf_bytes = finance_mod._build_invoice_pdf(inv, fin)
    assert pdf_bytes[:4] == b"%PDF"
    lines, txt = _total_line(pdf_bytes)
    assert lines, f"'TOTAL DUE' not found.\n{txt}"
    # The amount string must be on the SAME line
    line = lines[0].replace(" ", "").replace("\u00a0", "")
    assert "1,234,567.89" in line, f"7-digit total NOT on same line: {lines[0]!r}"


def test_invoice_pdf_total_due_single_line_8digit():
    inv, fin = _make(12345678.90)
    pdf_bytes = finance_mod._build_invoice_pdf(inv, fin)
    lines, txt = _total_line(pdf_bytes)
    assert lines, txt
    line = lines[0].replace(" ", "").replace("\u00a0", "")
    assert "12,345,678.9" in line or "12,345,678.90" in line, \
        f"8-digit total NOT on same line: {lines[0]!r}"


def test_invoice_pdf_logo_present_or_fallback():
    inv, fin = _make(50000.0)
    pdf_bytes = finance_mod._build_invoice_pdf(inv, fin)
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as doc:
        page1 = doc.pages[0]
        images = page1.images
        text = page1.extract_text() or ""
    has_image = len(images) > 0
    has_fallback = "PROJEXINO" in text.upper()
    assert has_image or has_fallback, \
        f"No logo image AND no PROJEXINO fallback text. images={len(images)}, text={text[:300]!r}"


def test_invoice_pdf_basic_metadata():
    inv, fin = _make(99999.99)
    pdf_bytes = finance_mod._build_invoice_pdf(inv, fin)
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as doc:
        full = "\n".join((p.extract_text() or "") for p in doc.pages)
    assert "INV-2026-7777" in full
    assert "TEST QA Client" in full
    assert "99,999.99" in full
